//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_tiet_SP
    {
        public int Ma_Size_Color { get; set; }
        public Nullable<int> MaMau { get; set; }
        public Nullable<int> MaSize { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaSP_ID { get; set; }
        public Nullable<int> MaNCC { get; set; }
    
        public virtual MAUSAC MAUSAC { get; set; }
        public virtual NhaCC NhaCC { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual SIZE SIZE { get; set; }
    }
}
