//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.SanPham_Mua = new HashSet<SanPham_Mua>();
        }
    
        public int MaHoaDon { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> MaTK { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<bool> XacNhan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham_Mua> SanPham_Mua { get; set; }
    }
}
