//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.SanPham_Mua = new HashSet<SanPham_Mua>();
            this.Chi_tiet_SP = new HashSet<Chi_tiet_SP>();
        }
    
        public int MaSP_ID { get; set; }
        public Nullable<int> MaDMSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string URL_Hinh_Anh { get; set; }
        public string NhanXet { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public Nullable<int> LuotMua { get; set; }
    
        public virtual DanhMuc_SP DanhMuc_SP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham_Mua> SanPham_Mua { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_tiet_SP> Chi_tiet_SP { get; set; }
    }
}
