//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_Mua
    {
        public int MaSP_Mua { get; set; }
        public Nullable<int> MaSP_ID { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> masize { get; set; }
        public Nullable<int> mamau { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual MAUSAC MAUSAC { get; set; }
        public virtual SIZE SIZE { get; set; }
    }
}
